import type { ProviderProfile } from '@sprint-coder/contracts';

const REVIEWED_AT = '2026-07-28T00:00:00.000Z';
const BEARER = { headerName: 'Authorization', scheme: 'Bearer' } as const;

export const PACK_A_PROVIDER_PROFILES: readonly ProviderProfile[] = [
  {
    id: 'mistral',
    displayName: 'Mistral API',
    baseUrl: 'https://api.mistral.ai/v1',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: '/models',
    curatedModels: [],
    verificationModel: null,
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference: 'https://docs.mistral.ai/resources/migration-guides',
    reviewedAt: REVIEWED_AT,
  },
  {
    id: 'deepseek',
    displayName: 'DeepSeek API',
    baseUrl: 'https://api.deepseek.com',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: '/models',
    curatedModels: [],
    verificationModel: null,
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference: 'https://api-docs.deepseek.com/guides/function_calling/',
    reviewedAt: REVIEWED_AT,
  },
  {
    id: 'groq',
    displayName: 'GroqCloud API',
    baseUrl: 'https://api.groq.com/openai/v1',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: '/models',
    curatedModels: [],
    verificationModel: null,
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference: 'https://console.groq.com/docs/openai',
    reviewedAt: REVIEWED_AT,
  },
];

export const PACK_B_PROVIDER_PROFILES: readonly ProviderProfile[] = [
  {
    id: 'moonshot',
    displayName: 'Moonshot AI API',
    baseUrl: 'https://api.moonshot.ai/v1',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: '/models',
    curatedModels: [],
    verificationModel: null,
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference: 'https://platform.kimi.ai/docs/api/overview',
    reviewedAt: REVIEWED_AT,
  },
  {
    id: 'minimax',
    displayName: 'MiniMax API',
    baseUrl: 'https://api.minimax.io/v1',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: '/models',
    curatedModels: [],
    verificationModel: null,
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference: 'https://platform.minimax.io/docs/api-reference/text-openai-api',
    reviewedAt: REVIEWED_AT,
  },
  {
    id: 'zhipu',
    displayName: 'Zhipu AI API',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: null,
    curatedModels: [{ id: 'glm-4.7', displayName: 'GLM-4.7' }],
    verificationModel: 'glm-4.7',
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference:
      'https://zhipu-ef7018ed.mintlify.app/api-reference/%E6%A8%A1%E5%9E%8B-api/%E5%AF%B9%E8%AF%9D%E8%A1%A5%E5%85%A8',
    reviewedAt: REVIEWED_AT,
  },
  {
    id: 'nvidia-nim',
    displayName: 'NVIDIA NIM API',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    baseUrlConfigurable: true,
    protocol: 'chat_completions',
    modelsPath: '/models',
    curatedModels: [],
    verificationModel: null,
    authentication: BEARER,
    requiredCredentialFields: [],
    errorOverrides: [],
    sourceReference:
      'https://docs.nvidia.com/nim/large-language-models/latest/api-reference.html',
    reviewedAt: REVIEWED_AT,
  },
  {
    id: 'cloudflare-workers-ai',
    displayName: 'Cloudflare Workers AI',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1',
    baseUrlConfigurable: false,
    protocol: 'chat_completions',
    modelsPath: null,
    curatedModels: [
      {
        id: '@cf/meta/llama-3.1-8b-instruct',
        displayName: 'Llama 3.1 8B Instruct',
      },
    ],
    verificationModel: '@cf/meta/llama-3.1-8b-instruct',
    authentication: BEARER,
    requiredCredentialFields: ['account_id'],
    errorOverrides: [],
    sourceReference:
      'https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/',
    reviewedAt: REVIEWED_AT,
  },
];

export const BUNDLED_PROVIDER_PROFILES: readonly ProviderProfile[] = [
  ...PACK_A_PROVIDER_PROFILES,
  ...PACK_B_PROVIDER_PROFILES,
];
